import Head from 'next/head'

export default function Home() {






  return (
    <div>
      <Head>
        <title>Hill Valley Production</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>











      <h2 className="text-4xl ">Hello World</h2>





    </div>






  )
}
